version: '3'

services:
  mysql:
    container_name: mysql_wake_up
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: jik
      MYSQL_PASSWORD: jesusisking
      MYSQL_DATABASE: wake_up
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis
    container_name: redis_wake_up
    hostname: jik
    command: redis-server --port 6379
    ports:
      - "6379:6379"