cloud:
  aws:
    s3:
      bucket: peace-img-bucket # 버킷 이름
    region:
      static: ap-northeast-2  # 리전 정보
    stack:
      auto: false
    credentials:
      instanceProfile: true   # AWS CLI에서 aws configure list 정보를 반영할건지 여부